# flake8: noqa
# This file was auto-generated with ChipStream/ui/run_uic.sh.
# Form implementation generated from reading ui file './dlg_model_props.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(467, 370)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_hash = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_hash.setReadOnly(True)
        self.lineEdit_hash.setObjectName("lineEdit_hash")
        self.gridLayout.addWidget(self.lineEdit_hash, 4, 1, 1, 1)
        self.lineEdit_date = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_date.setReadOnly(True)
        self.lineEdit_date.setObjectName("lineEdit_date")
        self.gridLayout.addWidget(self.lineEdit_date, 3, 1, 1, 1)
        self.lineEdit_id = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_id.setReadOnly(True)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.gridLayout.addWidget(self.lineEdit_id, 2, 1, 1, 1)
        self.lineEdit_path = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_path.setReadOnly(True)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.gridLayout.addWidget(self.lineEdit_path, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_name.setReadOnly(True)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.lineEdit_params = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_params.setReadOnly(True)
        self.lineEdit_params.setObjectName("lineEdit_params")
        self.gridLayout.addWidget(self.lineEdit_params, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.plainTextEdit_descr = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_descr.setReadOnly(True)
        self.plainTextEdit_descr.setBackgroundVisible(False)
        self.plainTextEdit_descr.setObjectName("plainTextEdit_descr")
        self.verticalLayout.addWidget(self.plainTextEdit_descr)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Model Properties"))
        self.label_4.setText(_translate("Dialog", "Date"))
        self.label_6.setText(_translate("Dialog", "Hash"))
        self.label_3.setText(_translate("Dialog", "Name"))
        self.label_5.setText(_translate("Dialog", "ID"))
        self.label.setText(_translate("Dialog", "Path"))
        self.label_2.setText(_translate("Dialog", "Params"))
